{% set version = "0.8-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vcdextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcdExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcdExtra/vcdExtra_{{ version }}.tar.gz
  sha256: 51cca108752d9a944964531bfa68607f7ecc2183d9e4d5a0d0bd639bcf333a0c

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ca
    - r-dplyr
    - r-glue
    - r-gnm >=1.0.3
    - r-here
    - r-mass
    - r-purrr
    - r-readxl
    - r-stringr
    - r-tidyr
    - r-vcd
  run:
    - r-base
    - r-ca
    - r-dplyr
    - r-glue
    - r-gnm >=1.0.3
    - r-here
    - r-mass
    - r-purrr
    - r-readxl
    - r-stringr
    - r-tidyr
    - r-vcd

test:
  commands:
    - $R -e "library('vcdExtra')"           # [not win]
    - "\"%R%\" -e \"library('vcdExtra')\""  # [win]

about:
  home: https://friendly.github.io/vcdExtra/
  dev_url: https://github.com/friendly/vcdExtra
  license: GPL-2.0-or-later
  summary: Provides additional data sets, methods and documentation to complement the 'vcd' package for Visualizing Categorical Data and the 'gnm' package for Generalized Nonlinear Models. In particular, 'vcdExtra' extends mosaic, assoc and sieve plots from 'vcd' to handle 'glm()' and 'gnm()' models and adds a 3D version
    in 'mosaic3d'.  Additionally, methods are provided for comparing and visualizing lists of 'glm' and 'loglm' objects. This package is now a support package for the book, "Discrete Data Analysis with R" by Michael Friendly and David Meyer.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
