{% set version = "0.8.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vcdextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcdExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcdExtra/vcdExtra_{{ version }}.tar.gz
  sha256: c4ce4caaa5008f835ad9a575bdeb3f0d40358d8a8cc4aa095f2cc0ae4426f4e8

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-ca
    - r-gnm >=1.0_3
    - r-rgl
    - r-vcd
  run:
    - r-base
    - r-mass
    - r-ca
    - r-gnm >=1.0_3
    - r-rgl
    - r-vcd

test:
  commands:
    - $R -e "library('vcdExtra')"           # [not win]
    - "\"%R%\" -e \"library('vcdExtra')\""  # [win]

about:
  home: https://friendly.github.io/vcdExtra/
  dev_url: https://github.com/friendly/vcdExtra
  license: GPL-2.0-or-later
  summary: Provides additional data sets, methods and documentation to complement the 'vcd' package for Visualizing Categorical Data and the 'gnm' package for Generalized Nonlinear Models. In particular, 'vcdExtra' extends mosaic, assoc and sieve plots from 'vcd' to handle 'glm()' and 'gnm()' models and adds a 3D version
    in 'mosaic3d'.  Additionally, methods are provided for comparing and visualizing lists of 'glm' and 'loglm' objects. This package is now a support package for the book, "Discrete Data Analysis with R" by Michael Friendly and David Meyer.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
