{% set version = "0.8-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vcdextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcdExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcdExtra/vcdExtra_{{ version }}.tar.gz
  sha256: c47a62f707595e82f74f72cef4d3c435f4efa21c75b77231533ce5ae68ca1da8

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-ca
    - r-gnm >=1.0.3
    - r-vcd
  run:
    - r-base
    - r-mass
    - r-ca
    - r-gnm >=1.0.3
    - r-vcd

test:
  commands:
    - $R -e "library('vcdExtra')"           # [not win]
    - "\"%R%\" -e \"library('vcdExtra')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=vcdExtra
  license: GPL-2.0-or-later
  summary: Provides additional data sets, methods and documentation to complement the 'vcd' package for Visualizing Categorical Data and the 'gnm' package for Generalized Nonlinear Models. In particular, 'vcdExtra' extends mosaic, assoc and sieve plots from 'vcd' to handle 'glm()' and 'gnm()' models and adds a 3D version
    in 'mosaic3d'.  Additionally, methods are provided for comparing and visualizing lists of 'glm' and 'loglm' objects. This package is now a support package for the book, "Discrete Data Analysis with R" by Michael Friendly and David Meyer.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
