travis:
  secure:
    BINSTAR_TOKEN: uHTQXn9msUtPr3rMyqJX5EQT5KnaQs58wPT7PWVW+VniICcts5W6Fmnd0t+nTnYlPErO24n5mMJ4x86LEQgXkmJBktwhQdQnHKOCTeThXleCmWpB1IKYM66eySB7JLOC5jIi4kKJpvpZr5LsZaFwXrMQDmsjqGi+QAY7BHjz0YRNzqtGK1RycaHR0guBMt2DZJzjwz/BlaLOvCgmzwkmz9mmEqLpZxijzivcVgHh9ON2zZBwOPwPqf58DiugB19wFeb6uFZ0T9tg8EVcCohB7mNqk1H3k1hklnesfvr7Nx+4drVoHLr55cBB763J5z8iPF65gS7rZ0eU/D/QPvB586IS6eISQ3X/EFCLaMFN6uP2E5LfIYHyMHbNFo7BpHew3YJTWPnJ8ZvTbKeOg1mcFiV3A8Xw4/o2qOJSSP9oPp/vbRkmqVT+zGuq7CIw3vlg/R5R+gWWtGmESRSmLLrXUCnrnOFOrF+t5VfgLbLQ0TemUiY6JYcaPEm7tOrZ1MtqeX7gbRqp6fESgZs+mvqdVfUQZ4fVPZu599eHfUmnBoTHljfBoIUeu1aNbGnjsw6RQefmb+erYEvKLFsJJijGbirKK3VBQXGit84cnRxFlxx+uTZo04V7qrzDSgGcx7ANX1OlfhXTCFjszqC1I2tPxp+s2wtDeUmGAzA2morHwcw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
