appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: VbQSB/mWmxTRjrJBhGxZnmnStOVhuXn0OCOeQDBWLZNgtJtr07QULZtQLse4fn6Erx64j5LXABDLFE6/fFMSyKzVxCx7PaJ6F3WSh15JuuyB3y7aEeu2wDxBA67JrtLw/Z45vQ3SJOBfXTY0BVOIkatGrsDDzzpSBB+JiSlP3F9qJR4SH8RRfKVBsXp1d+/9/+pfGGEGa94l1a2ajeK41FEYJnGUfhPBlksmH1n0YbtdsXUdFW59FYZJZbcSDPEkiVoulEXFx/yPlumxaA0Wavyv8oz1nMo4gSjhV205JRaV9VKf6VixuFNmgy4emiLs4De0mH7+VWiaQU2g6NNvdTd2Z7POlsomAqUd7GuPSHejd9ryi0mNRPWsWrtuFvtBeBgOy5kJoyioE1OAcQwlBps3IzPfCoXClV8URH24Oug3IFfFAi7SEiGHBWxZ0JSwUlw3MwagtFvpuE324eyRYuszUo/9MRTj81epQa9lXaPIAMJwyrG9uJ2VmBtTQafyR/VuROam0XdTVRw5ncTVEdCMHH0NiS/395Ibq2N9jxPn9pfKZzR2gpGf1XLgqU3A7rhOoIWVT/aYr1HMsZRNRQ+P11iVs/xwV2dqAxIrl8yUlwF9xleAke4YtmpvwJ1DeIQbTygx13taHDAETAD0z++Kee/DMHxpthpo7cBe71o=}
bot:
  automerge: true
